### ISSUE TITLE
Hardcoded addresses

### ISSUE THREAD

**Issue by virtualalchemyb** [codeesura/arbitrum-claim-send#2]
Hello and thanks for sharing your code.

Looking at your code, I see a lot of hardcoded addresses, it makes me wonder about the integrity of your project.
Are you sending the claimed tokens to your address? 

It does look that way, but Im not that experienced with blockchain, ARB and smart contracts yet, so please just take this as a question for more information. I do have a lot of experience in programming, I am just being careful.

Thanks in advance for your response

**Comment by codeesura** [comment]
First of all, thank you and yes you're right. After the ARB claim, the wallet address to be sent was stored as my own wallet address, and I assigned this address to a variable called "recipientAddress," assuming that the person using it would change it. You're right, I should have corrected this. The other addresses are present in the "contractAddress" variable, which holds the ARB claim contract address, and in the "getBlockAddress" section, the contract address that communicates with L1 and retrieves the latest block data. The purpose of the code is to enable individuals whose wallets have been hacked or stolen to claim the ARB airdrop and transfer it to their secure wallets.

Fix this : https://github.com/codeesura/arbitrum-claim-send/commit/3e76c7512853bda4730df81bac07d27d59ff288c

**Comment by codeesura** [comment]
https://github.com/codeesura/arbitrum-claim-send/commit/3e76c7512853bda4730df81bac07d27d59ff288c
