### ISSUE TITLE
Package.json + questions

### ISSUE THREAD

**Issue by virtualalchemyb** [codeesura/arbitrum-claim-send#3]
Heya, 

I tried getting your repo up and running, but you seem to have forgotten your package.json / package-lock.json to your repository?

Apart from that, can you please explain to me how to configure the `const addresses` in your index.js?

I am wondering what `armut` means in the example and would love to help with improving the repo for you if you are open to that.

Best regards

**Comment by codeesura** [comment]
Hey,

Yes, I forgot to add the package.json file :( Added = https://github.com/codeesura/arbitrum-claim-send/commit/6ee210d1d26af7091ae5e7e239fd62ec78d14a8e

The main purpose of this code is to enable individuals who have qualified for the ARB airdrop but have had their wallets stolen or hacked to claim and transfer the ARB tokens in their wallets to another wallet before the hackers. 
```
 {
  armut: 'armut', // From address (the address where we can send ETH to the hacked wallet)
  senderAddress: 'senderAddress', // to address (hack wallet)
  armutPrivateKey: 'armutPrivateKey', // From wallet PK
  senderPrivateKey: 'senderPrivateKey', 
  claimAmount: 3750,  // the amount of ARB tokens airdrop
}
```

So , `armut` = from wallet
